services:
  ocp:
    image: ${OCP_IMAGE:-openpolicyagent/opa-control-plane:edge}
    command:
      - run
      - --addr=0.0.0.0:8282
      - --apply-migrations
      - --config=/ocp.yml
      - --data-dir=/tmp
      - --log-level=debug
    volumes:
      - ./ocp.yml:/ocp.yml
    ports:
      - 8282:8282
    environment:
      - OCP_TLS_CERT
      - OCP_TLS_KEY
    depends_on:
      - db

  s3proxy:
    image: andrewgaul/s3proxy:3.0.0
    ports:
      - 8080:80
    environment:
      - S3PROXY_AUTHORIZATION=none
      - JCLOUDS_PROVIDER=transient-nio2

  s3proxy-init:
    image: alpine/curl
    volumes:
      - ./init-s3.sh:/init-s3.sh
    entrypoint: /bin/sh
    command: ["/init-s3.sh"]
    depends_on:
      - s3proxy

  db:
    image: postgres:18-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: sesame
    ports:
      - 5432:5432
    volumes:
      - ./init-pg.sh:/init-pg.sh
      - ./tls:/etc/ssl/postgresql/
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    entrypoint: "/init-pg.sh"
    command: -c ssl=on -c ssl_cert_file=/etc/ssl/postgresql/server-cert.pem -c ssl_key_file=/etc/ssl/postgresql/server-key.pem -c hba_file=/etc/postgresql/pg_hba.conf

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090 # http://localhost:9090

  opa:
    image: openpolicyagent/opa:latest-static
    volumes:
      - ./opa.yml:/opa.yml
    ports:
      - 8181:8181
    command:
      - run
      - --server
      - --addr=:8181
      - --log-level=debug
      - --config-file=/opa.yml
    environment:
      AWS_ACCESS_KEY_ID: anonymous
      AWS_SECRET_ACCESS_KEY: anonymous
      AWS_REGION: us-east-1
