package authz

import (
	"context"
	"database/sql"
)

// Authorizer defines the interface for making authorization decisions.
type Authorizer interface {
	// Check determines if a given access request is permitted for a single resource.
	Check(ctx context.Context, tx *sql.Tx, fn ArgFn, accessDescriptor AccessDescriptor) bool
	// Partial generates a SQL expression (a WHERE clause) that can be used to
	// filter a list of resources based on the user's permissions.
	Partial(ctx context.Context, accessDescriptor AccessDescriptor, extraColumnMappings map[string]SQLColumnRef) (Expr, error)
}

type ArgFn func(int) string

// SQLTableRef represents a reference to a SQL table.
type SQLTableRef struct {
	Table string
}

func (st SQLTableRef) SQL(_ ArgFn, args []any) (string, []any) {
	return st.Table, args
}

// SQLColumnRef represents a reference to a specific column in a SQL table.
type SQLColumnRef struct {
	Table  string
	Column string
}

func (sc SQLColumnRef) Tables() []SQLTableRef {
	return []SQLTableRef{{Table: sc.Table}}
}

func (sc SQLColumnRef) SQL(fn ArgFn, args []any) (string, []any) {
	return sc.Table + "." + sc.Column, args
}

// Expr represents a SQL expression generated by partial evaluation.
type Expr interface {
	SQL(ArgFn, []any) (string, []any)
	Tables() []SQLTableRef
}

// AccessDescriptor describes the context of an access request.
type AccessDescriptor interface {
	Principal() string
	Tenant() string
	Resource() string
	Permission() string
	Name() string

	WithPrincipal(string) AccessDescriptor
	WithTenant(string) AccessDescriptor
	WithResource(string) AccessDescriptor
	WithPermission(string) AccessDescriptor
	WithName(string) AccessDescriptor
}

// AccessFactory defines a function to create an AccessDescriptor.
type AccessFactory func() AccessDescriptor
